### ISSUE TITLE
[Job] Farmer

### ISSUE THREAD

**Issue by zelytra** [zelytra/Histeria#158]

**Comment by rsclboss10** [comment]
![image](https://user-images.githubusercontent.com/83504702/156924387-e25b3f59-654c-49ee-9142-3d6420e12cf4.png)

Normal que le texte n'est pas en couleur ?

**Comment by rsclboss10** [comment]
![image](https://user-images.githubusercontent.com/83504702/156924408-2439f310-9ee5-465a-bd0b-a16f67247696.png)

Normal les " ? " ?

**Comment by rsclboss10** [comment]
![image](https://user-images.githubusercontent.com/83504702/156924441-3a1b0c97-9c56-4944-a8b9-6b46c4697e78.png)

Il manque pas un " d " à " diamon Hoe " ?

**Comment by zelytra** [comment]
> ![image](https://user-images.githubusercontent.com/83504702/156924408-2439f310-9ee5-465a-bd0b-a16f67247696.png)
> 
> Normal les " ? " ?

Manquais des loot aux reward, donc en attendant des "?" sont placé

**Comment by zelytra** [comment]
> ![image](https://user-images.githubusercontent.com/83504702/156924441-3a1b0c97-9c56-4944-a8b9-6b46c4697e78.png)
> 
> Il manque pas un " d " à " diamon Hoe " ?

Patch a la prochainne update

**Comment by zelytra** [comment]
> ![image](https://user-images.githubusercontent.com/83504702/156924387-e25b3f59-654c-49ee-9142-3d6420e12cf4.png)
> 
> Normal que le texte n'est pas en couleur ?

Nop, patch a la prochainne update
