### ISSUE TITLE
[Block] Core Mining Drill

### ISSUE THREAD

**Issue by zelytra** [zelytra/Histeria#162]
Déveloper ce nouveau block (dans le même style que le nocturite generator) Utilité ?

**Comment by rsclboss10** [comment]
- Tester le bloquage du craft de la drill quand pas lvl 100 miner         |  **OK  !**

**Comment by rsclboss10** [comment]
- Tester le craft du core mining drill (dernier message de rscl et provisoir) | **OK !**
