### ISSUE TITLE
[ Event Command ]

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#167]
Une commande /event create pour les admins, elle ouvrirait une interface qui permettrait de choisir entre différents évents exemples : purge, KOTH, 1vs1 etc. Des évents prédéfinies ce qui permettrait de les faire régulièrement. Un système qui nous permettrait de choisir l'heure à la quel nous voulons que l'évent start. Une fois l'évent choisi il enverra un message dans le chat minecraft du style "Évent {nom: event} start in {heure} !" et idem pour discord dans un channel spécifique avec un ping "évent". Les joueurs rejoignent grâce à une commande /event join et ils seront automatiquement mis dans une fille d'attente, une fois l'heure arrivée un dernier message disant que l'évent start et qu'ils seront Tp dans les {nombre} prochaines secondes.

**Comment by zelytra** [comment]
Ah ouais pas simple mais bonne idée !
