### ISSUE TITLE
[ Échange ]

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#174]
Faire une salle d'échange car pour le moment les gens vont dans l'arena pour échange :/

**Comment by zelytra** [comment]
Non. Ajout d'une commande avec interface d'échanges entre joueur en temp réelle

**Comment by rsclboss10** [comment]
Si on est full inventaire et que le trade est accepté, l'item ce fait clear.

**Comment by rsclboss10** [comment]
![image](https://user-images.githubusercontent.com/83504702/156925946-a1d9d855-2ebe-4c39-99c4-7e62d3bd4e07.png)

Normal qu'il n'ai pas de **[DECLINE]** ?

**Comment by zelytra** [comment]
Le fait que j'avais la flem de le dev, crée un ticket et ferme celui si tout marche

**Comment by rsclboss10** [comment]
ok ok
