### ISSUE TITLE
[Jobs] Miner

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#185]
Lorsqu'on casse deux minerais avec la pioche en histerite, nous obtenons l'xp pour un seul.

**Comment by rsclboss10** [comment]
Lorsqu'on casse les deux minerais nous obtenons bel et bien 65xp x 2 mais il n'affiche que 65xp gagné

**Comment by zelytra** [comment]
Ptn fais chié je pensais que t'allais pas remarqué. Chiant ce bug
