### ISSUE TITLE
[Henchant] Enchanted_book

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#187]
Mettre un message disant qu'il est impossible d'enchante au lvl 40 par exemple car l'enchante comporte un max lvl de {nombre}

ça en gros : 
![image](https://user-images.githubusercontent.com/83504702/153647563-0e42e5f6-f85c-40ef-a107-ddccf0d2ddaf.png)

**Comment by zelytra** [comment]
Je ne comprend pas le message t'indique deja les "bounds" etant deja les limite soit ici : min = 1 et max = 2

**Comment by rsclboss10** [comment]
https://youtu.be/W464pACQA-4

**Comment by zelytra** [comment]
Ok je viens de le re produir c'est un bug

**Comment by rsclboss10** [comment]
https://youtu.be/-Wr0nnH3V7I

Error : An error has occurred on server : .home.zelytra.Histeria3.faction.plugins.Histeria , please report this to an admin. org.bukkit.command.CommandException: Unhandled exception executing command 'henchant' in plugin Histeria v3.0
