### ISSUE TITLE
[ Suppression ] Mining Drill

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#195]
Lorsqu'on met des items autre que des minerais dedans, ils se font clear 

**https://youtu.be/6LD1T87ZDYQ**

**Comment by rsclboss10** [comment]
- Tester le craft du core mining drill (dernier message de rscl et provisoir) | **OK !**

**Comment by zelytra** [comment]
Que verrais tu comme comportement normal dans ce cas ? On laisse la suppression d'item ? On les fait drop par terre ?...

**Comment by rsclboss10** [comment]
Ils reviennent dans ton inventaire une fois que tu ferme l'interface et si ton inventaire et full, ils drops par terre

**Comment by rsclboss10** [comment]
https://youtu.be/VRaXTMX54HE

**Comment by zelytra** [comment]
Ptn tu saoul...

**Comment by rsclboss10** [comment]
Noice !
