### ISSUE TITLE
[ Drop ] Mining Drill 

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#198]
Il ne se récupère pas lorsqu'on le casse

https://user-images.githubusercontent.com/83504702/155334106-335a94be-4785-420e-91d3-d98a90c5a4e2.mp4

**Comment by rsclboss10** [comment]
Il ne se récupère pas au Hammer.

**Comment by zelytra** [comment]
En effet il ne doit pas se récupérer tout court par le hammer,ni par l'histerite pickaxe
