### ISSUE TITLE
Anvil- armures et outils (histerite et noctu)

### ISSUE THREAD

**Issue by watty506** [zelytra/Histeria#8]
On ne peut tout simplement pas récupérer l'armure de l'enclume _**seulement lorsque l'on essaye de la repair**_

Par la même occasion on ne peut pas rename et repair en même temps (sur les armures et outils en hist/noctu)

**Comment by zelytra** [comment]
Spigot pas a jours sur le serveur test
oui c'est normal il faut le faire hors repair
