### ISSUE TITLE
NPC

### ISSUE THREAD

**Issue by zelytra** [zelytra/Histeria#82]

**Comment by rsclboss10** [comment]
Oubli du nombre max de caractère dans un pseudo. (16)

**Comment by rsclboss10** [comment]
An error has occurred on server : .home.zelytra.Histeria2.beta.plugins.Histeria , please report this to an admin. org.bukkit.command.CommandException: Unhandled exception executing command 'npc' in plugin Histeria v2.0

Quand je fais  "/npc action {nom du npc} server" et que je ne met pas le nom genre beta ou faction.

**Comment by rsclboss10** [comment]
Quand je fais /npc action {Carglass} teleport 0 0 0 world_nether ou world_the_end et que je me tp, ensuite /spawn le npc disparais, j'ai beau cliquer partout c'est comme s'il n'était pas là mais quand je déco re co il respawn
