### ISSUE TITLE
[Freeze]

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#97]
**Procédure :** 

1. Freeze quelqu'un / sois même
2. changer de serveur

**Résultat :** 

Vous n'êtes plus freeze **uniquement** sur les autres serveur, si vous retourné sur le serveur où vous avez été freeze vous le serez toujours.

**Comment by zelytra** [comment]
Pas un bug, c'est le fonctionnement normal du Freeze. Il est normalementimpossible que le joueur freeze (hors staff) puisse switch
