### ISSUE TITLE
[arena chest]

### ISSUE THREAD

**Issue by rsclboss10** [zelytra/Histeria#99]
Nous avons fais plein de coffre d'arène ensuite spam refill et après nous les avons retiré et là quand on fait /arenachest nous voyons qu'il reste 2 coffres aux mêmes co et sa fais une error "An error has occurred on server : .home.zelytra.Histeria2.beta.plugins.Histeria , please report this to an admin. org.bukkit.command.CommandException: Unhandled exception executing command 'arenachest' in plugin Histeria v2.0"

**Comment by zelytra** [comment]
Non reproductible
